DC: str = ''
PASSWORD: str = ''
PHONE: str = '+380xxxxxxxxx'
EMAIL: str = 'test@gmail.com'
VEHICLE: str = 'school'  # school, tsc
TRANSMISSION: str = 'automatic'  # manual, automatic
DATES: list[str] = ['01.11', '02.11', '03.11']
TIME: str = '12:00'
TSC: str = '8049'
